name: Build and package docker image

on:
  push:
    branches: [ "main" ]
env:
  PROJECT_ID: prj-dinum-data-templates-66aa
  REGION: europe-west1
  IMAGE_NAME: ${{ vars.GCP_REGION}}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID}}/template-repository/${{ vars.PROJECT_NAME }}-function
jobs:
  deploy:
    permissions:
      contents: read
      packages : write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: "access_token"
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.GCP_REGION}}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
